# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeWaiting',
            fields=[
                ('doctor', models.IntegerField(primary_key=True, serialize=False)),
                ('minutes_waiting', models.IntegerField()),
                ('total_patients', models.IntegerField()),
            ],
        ),
    ]
